### ISSUE TITLE
How to obtain the depth images

### ISSUE THREAD

**Issue by mohit1485** [noahzn/FoHIS#2]
As the code requires the RGB Image and the Depth image to simulate fog effects.  how to obtain Depth images

**Comment by noahzn** [comment]
> As the code requires the RGB Image and the Depth image to simulate fog effects. how to obtain Depth images

Hi mohit1485, for the depth maps you can generate some using existing depth estimation methods or you can collect your own depth images. You can try open-sourced depth data set as well.
