### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by YQ-Yang** [noahzn/FoHIS#4]
Hello,thank you for your work.
And i want to ask you that how can i get the depth images? Is that can generate from rgb images?

**Comment by noahzn** [comment]
Hi @YQ-Yang, you can use any existing depth estimation methods to generate the depth maps.

**Comment by YQ-Yang** [comment]
> Hi @YQ-Yang, you can use any existing depth estimation methods to generate the depth maps.

thank you for your reply.
is the Pseudo color depth map image can work too?i have tried but can't get good result

**Comment by YQ-Yang** [comment]
> Hi @YQ-Yang, you can use any existing depth estimation methods to generate the depth maps.

Thank you for your reply.
And  there is another question i want to ask :how to change the fog density?

**Comment by noahzn** [comment]
You can adjust `const.VISIBILITY_RANGE_MOLECULE` and `const.VISIBILITY_RANGE_AEROSOL` in `FoHIS/parameter.py`
