### ISSUE TITLE
I can't train new pictures

### ISSUE THREAD

**Issue by Chengyunlai** [noahzn/FoHIS#5]
Hi, thank you for your contribution. Now I have a question to ask: I want to add simulation to the new image, but I found that there is an IMgd.jpg in the sample image, how to generate the IMgd.jpg? Hope to answer my doubts, thank you very much!

**Comment by noahzn** [comment]
Hi, 
imgd. jpg is the depth image that you need to prepare so that the algorithm can use it to generate the foggy image. 
There are some open-sourced datasets containing rgb+depth image pairs. Or you can use some CNN-based methods to generate your own depth images.

**Comment by Chengyunlai** [comment]
Thank you for response to our questions so swiftly!
`img = '../img/The same name.jpg'`
`depth = cv2.imread('../img/The same name.jpg')[:, :, 0].astype(np.float64)`
I'm now trying to make both inputs the same image, It feels like it's directly increasing the exposure of the image. I will take the solution you mentioned in the future. Thanks again!
