### ISSUE TITLE
compute_authenticity.py issues

### ISSUE THREAD

**Issue by djdll** [noahzn/FoHIS#7]
I used the code you provided to calculate the image authenticity index for my graph, but the result is sometimes one and sometimes not in the range 1-5. I want to ask which hyperparameter I need to adjust to calculate the correct data. Thank you for your work

**Comment by noahzn** [comment]
Hi, thanks for your interest in our work! Since this repo was released 7 years ago, I don't really remember the details of my code. You could try using an older version of `Numpy` and see if this could solve your problem.

**Comment by noahzn** [comment]
I am now closing this issue because of no response.
